### PR TITLE
[JENKINS-10160] Update jmdns to 3.5.3

### PR DESCRIPTION
**Pull request by PatrickRose**
I need to do further tests on this, but this is the initial work to update jmdns to 3.5.3 from 3.4.0 and readd the patches.

The patches I generated by going through the history on master and readding the ones that looked like they now apply after jmdns has been updated - though I'll admit that I haven't done a lot of thorough testing on this!

I think that _actually_ what should be done is do a proper fork of jmdns now that it's on github but that's up to you guys!

### CODE REVIEW

**Comment by PatrickRose** [comment]
Ping @kohsuke - is there anything extra I can do to get the ball rolling on this?

**Comment by oleg-nenashev** [comment]
This is a pretty legacy hardfork, likely migrated from SVN years ago. There was no updates since 2011, and I had no idea about this repo existence before [JENKINS-50812](https://issues.jenkins-ci.org/browse/JENKINS-50812). CI is also not relevant, we also moved to the new CI instance...

I will take a look what we can do with that. https://github.com/jenkinsci/jmdns/pull/2/commits/93420c0f6688a7565e6905d358c3b9b56bfecae3 also adds some incompatible changes like `JmDNS#abort()`, and it needs careful approach (can be solved by Java 8 tho).

Just in case, it is recommended to ping @jenkinsci/code-reviewers for such cases or raise a thread in the developer mailing list.

**Comment by PatrickRose** [comment]
@oleg-nenashev  - thanks for taking a look, it wasn't clear what I should be doing (I've been periodically prodding this on JENKINS-10160 without much response).

My understanding is that the abort method is a non-blocking version of the `JmDNS#close` method (see 4d56e6f)

**Comment by oleg-nenashev** [comment]
For me compilation of this PR just fails with

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project jmdns: Compilation failure: Compilation failure: 
[ERROR] /Users/nenashev/Documents/jenkins/libs/jmdns/src/main/java/javax/jmdns/impl/JmDNSImpl.java:[1847,31] cannot find symbol
[ERROR]   symbol:   variable Level
[ERROR]   location: class javax.jmdns.impl.JmDNSImpl
[ERROR] /Users/nenashev/Documents/jenkins/libs/jmdns/src/main/java/javax/jmdns/impl/JmDNSImpl.java:[1848,19] cannot find symbol
[ERROR]   symbol:   method finer(java.lang.String)
[ERROR]   location: variable logger of type org.slf4j.Logger
[ERROR] /Users/nenashev/Documents/jenkins/libs/jmdns/src/main/java/javax/jmdns/impl/JmDNSImpl.java:[1856,19] cannot find symbol
[ERROR]   symbol:   method finer(java.lang.String)
[ERROR]   location: variable logger of type org.slf4j.Logger
[ERROR] /Users/nenashev/Documents/jenkins/libs/jmdns/src/main/java/javax/jmdns/impl/JmDNSImpl.java:[1870,19] cannot find symbol
[ERROR]   symbol:   method finer(java.lang.String)
[ERROR]   location: variable logger of type org.slf4j.Logger
[ERROR] /Users/nenashev/Documents/jenkins/libs/jmdns/src/main/java/javax/jmdns/impl/JmDNSImpl.java:[1883,35] cannot find symbol
[ERROR]   symbol:   variable Level
[ERROR]   location: class javax.jmdns.impl.JmDNSImpl
[ERROR] /Users/nenashev/Documents/jenkins/libs/jmdns/src/main/java/javax/jmdns/impl/JmDNSImpl.java:[1884,23] cannot find symbol
[ERROR]   symbol:   method finer(java.lang.String)
[ERROR]   location: variable logger of type org.slf4j.Logger

```

**Comment by rhertzog** [comment]
Can we get the ball rolling again? It would be nice to see https://issues.jenkins-ci.org/browse/JENKINS-10160 fixed. An any case, thanks for picking up on this, I have been bitten multiple times by this problem and I'm looking forward for a fix.

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
it cannot be considered for merging while compilation fails. If somebody has capacity to work on it, contributions will be appreciated

**Comment by furai** [comment]
I'm sorry to just bump it with no contribution but I'm really desperate. I've never really touched java or jenkins code so I can't fix this myself. Did anyone of the core dev team look into it?

**Comment by oleg-nenashev** [comment]
I took a look at it, and I understand why it is important. OTOH, I do not understand why are the custom patches are needed on the Jenkins side anymore. There is no history in Git, so I cannot easily say what were the custom changes, why they were needed, and what is going to be broken by this PR. It would take a while to investigate.

Maybe replacing this to the official https://github.com/jmdns/jmdns release is a way to go for the Jenkins core. As a core maintainer I recommend going forward with this approach.

CC @jenkinsci/core and @jenkinsci/code-reviewers . Maybe somebody remembers something about this repo.

**Comment by PatrickRose** [comment]
From what I can work out, it just adds a non blocking variant of the abort method based on a diff between the jmds version and this repo.

I do keep meaning to come back to this and fix the compilation errors but I've been busy.

**Comment by oleg-nenashev** [comment]
Would it be possible to just upstream the patch so that we forget about a
custom fork?
I believe it would be the simplest way to go.

Otherwise we may need to reestablish the CI and delivery flow for this repo.

BR, Oleg

**Comment by PatrickRose** [comment]
Probably! I don't know too much about what this adds which is why I tagged @kohsuke

**Comment by oleg-nenashev** [comment]
Gentle ping @kohsuke . 
My proposal would be to go YOLO and to update the dependency to the upstream version in the Jenkins core. If it works, one repo less to worry about.

CC @daniel-beck @jenkinsci/core @batmat

**Comment by PatrickRose** [comment]
Iirc, the change in this hard fork adds a non-blocking shutdown method - that change might need to be sent upstream?

**Comment by fcojfernandez** [comment]
I've just opened https://github.com/jenkinsci/jenkins/pull/4021, which should ease this update and  future ones.

**Comment by PatrickRose** [comment]
@fcojfernandez - should I close this PR then?

**Comment by fcojfernandez** [comment]
@PatrickRose let's wait for the feedback from the community. Mine hasn't been reviewed yet

**Comment by oleg-nenashev** [comment]
Closing this PR since https://github.com/jenkinsci/jenkins/pull/4021 was merged.
Thanks @PatrickRose for the PR and for the reviews!

**Pull request closed without merging**
